[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/FenrisOwO"

    [social.params]
        icon = "custom-github-logo"
        newTab = true

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com/fenrisfree"

    [social.params]
        icon = "custom-twitter-logo"
        newTab = true




[[social]]
    identifier = "QQ"
    name       = "QQ"
    url        = "https://qm.qq.com/cgi-bin/qm/qr?k=Mlxr6DFkkg_pFThhU10KrtWdSrErrPu4&noverify=0"

    [social.params]
        icon = "custom-qq_logo_icon_238099"
        newTab = true


[[social]]
    identifier = "Bilibili"
    name       = "Bilibili"
    url        = "https://space.bilibili.com/174863977"

    [social.params]
        icon = "custom-television-simple"
        newTab = true
